config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resources :itineraries, only: [:index, :show] do
    resources :trips, only: [:new, :create]
  end

  resources :trips, only: [:show, :index, :edit, :update] do
    resources :messages, only: [:index, :new, :create, :update, :edit]
    resources :user_trips, only: [:create]
  end

  resources :user_trips, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  get "my_trips", to: "trips#my_trips"

end

app/models/itinerary.rb
class Itinerary < ApplicationRecord

  include AlgoliaSearch

  algoliasearch do
  end

  ACTIVITIES_MAPPING = {"skitouring" => "Ski de randonnée",
                        "snow_ice_mixed" => "Mixte et glace",
                        "mountain_climbing" => "Alpinisme",
                        "rock_climbing" => "Grande voie",
                        "ice_climbing" => "Cascade de glace"
                       }

  has_many :trips, dependent: :destroy
  validates :title, presence: true
  geocoded_by :address, latitude: :coord_lat, longitude: :coord_long # ActiveRecord
  # after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :init_mark_down_parser, only: :show

  def index
    if params[:address].present? && params[:activity].present?
      @itineraries = Itinerary.near(params[:address], 300).order("distance")
      @itineraries = @itineraries.select { |itinerary| itinerary.activities.include?(params[:activity]) }
    else
      @itineraries = Itinerary.all
    end

    @markers = @itineraries.map do |itinerary|
      {
        lng: itinerary[:coord_long],
        lat: itinerary[:coord_lat],
        infoWindow: render_to_string(partial: "infowindow", locals: { itinerary: itinerary }),
        image_url: helpers.asset_url('https://png.pngtree.com/svg/20170116/mountain__1201096.png')
      }
    end
  end

  def show
    @itinerary = Itinerary.find(params[:id])
  end

  private

  def init_mark_down_parser
    renderer = Redcarpet::Render::HTML.new(no_images: true)
    @markdown = Redcarpet::Markdown.new(renderer)
  end
end

app/views/itineraries/_description.html.erb
<div id="itinerary-content">
  <%= @markdown.render(itinerary.content.gsub(/\[img.*\[\/img\]/,'')).html_safe %>
</div>

app/views/itineraries/_infowindow.html.erb
<h3><%= itinerary.title %></h3>
<h4>
  <%= itinerary.activities.join(", ") %>
</h4>
<%= link_to "Plus d'infos...", itinerary_path(itinerary) %>

app/views/itineraries/_mapbox.html.erb
<div
  id="map"
  style="
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
>
</div>

app/views/itineraries/index.html.erb
<div class="container itinerary">
  <h2>Quel itinéraire voulez-vous proposer?</h2>
</div>

<ul class="list-inline tabs-underlined">
  <li>
      <input id="algoliaSearch" class="form-control tab-underlined active" type="search" placeholder="Affiner ma recherche" aria-label="Search" style="border: 1px solid black; color: black; width: 200px">
  </li>
  <li>
    <a href="#" class="tab-underlined active" id="tab-list">Liste</a>
  </li>
  <li>
    <a href="#" class="tab-underlined" id="tab-map">Carte</a>
  </li>
</ul>


<div class="container" id="content-list">
  <div class="row">
    <% @itineraries.each do |itinerary|  %>
      <div class="col-xs-12 col-sm-6 col-md-4" style="padding: 10px;">
        <div class="card trip-element" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= itinerary.picture_url %>');">
          <%= link_to('', itinerary_path(itinerary), class: "card-link") %>
          <div class="card-category card-element-invisible"><%= itinerary.activities.join(", ") %></div>
          <div class="card-description">
            <div class="card-infos">
              <h2><%=itinerary.title %></h2>
              <%= link_to('', itinerary_path(itinerary), class: "card-link") %>
              <% Itinerary::ACTIVITIES_MAPPING.map do |k, v|%>
                <% if k == itinerary.activities.first  %>
                  <p><%= v %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container" id="content-map" hidden>
  <%= render partial: "mapbox" %>
</div>

app/views/itineraries/show.html.erb
<div class="container">
  <div class="flex-container">
   <div class="flex-object">
    <div class="card-iti">
      <%= image_tag @itinerary.picture_url %>
      <div class="card-category">
        <%= @itinerary.activities.join(", ") %>
      </div>
      <div class="card-iti-description card-iti-element-invisible">
        <ul class="list-group">
        <li class="list-group-item trans">

          <h4 class="text-center"><%= @itinerary.title %></h4>

          </li>
        <% if @itinerary.diffculty != nil %>
          <li class="list-group-item trans">Difficulté: <%= @itinerary.diffculty %></li>
        <% end %>
        <% if @itinerary.elevation_max != nil %>
          <li class="list-group-item trans">Altitude maximale: <%= @itinerary.elevation_max %>mètres</li>
        <% end %>

        <% if @itinerary.height_diff_up != nil %>
          <li class="list-group-item trans">Dénivelé: <%= @itinerary.height_diff_up %>mètres</li>
        <% end %>

        <% if @itinerary.number_of_outings != nil %>
          <li class="list-group-item trans">Outings: <%= @itinerary.number_of_outings %></li>
        <% end %>
      </ul>
      </div>
      <div>
        <%= link_to('Créer une sortie', new_itinerary_trip_path(@itinerary), class: "btn btn-primary card-button btn-lg outline") %>
      </div>
    </div>
  </div>
  <div class="flex-object trip-element description">
    <h4>Description</h4>
    <%= render partial: "./itineraries/description", locals: {itinerary: @itinerary} %>
  </div>
  <div class="flex-object">
    <iframe src=<%= "https://fatmap.com/@#{@itinerary.coord_lat},#{@itinerary.coord_long},#{@itinerary.elevation_max},-35.9049826,92.6848191,2388.9221056,normal" %> frameborder="" allowfullscreen="" width="100%" height="600"></iframe>
  </div>
</div>
</div>