config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resources :itineraries, only: [:index, :show] do
    resources :trips, only: [:new, :create]
  end

  resources :trips, only: [:show, :index, :edit, :update] do
    resources :messages, only: [:index, :new, :create, :update, :edit]
    resources :user_trips, only: [:create]
  end

  resources :user_trips, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  get "my_trips", to: "trips#my_trips"

end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :itinerary
  has_many :user_trips, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/controllers/trips_controller.rb
require 'nokogiri'
require 'open-uri'

class TripsController < ApplicationController
  before_action :init_mark_down_parser, only: :show

  def index
    if params[:activity].present?
      @trips = Trip.all.order('trips.created_at desc').select { |trip| trip.itinerary.activities.include?(params[:activity]) }
    else
      @trips = Trip.all.order('trips.created_at desc')
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @user_trip = UserTrip.new
    @users = @trip.user_trips.where(state: "accepté").map { |user_trip| user_trip.user }
    @message = Message.new
  end

  def new
    @trip = Trip.new
    @trip.itinerary = @itinerary
    @trip.user = current_user
    @itinerary = Itinerary.find(params[:itinerary_id])
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    @trip.save
    @trip.itinerary = Itinerary.find(params[:itinerary_id])
    @trip.user = current_user
    @trip.save!
    redirect_to trips_path
  end

  def my_trips
    @my_trips = Trip.where(user_id: current_user.id).order('trips.created_at desc')

    #    .first
  end

  # def validate_user_for_trip
  #   @trip = Trip.find(params[:id])
  #   @trip.user_trip = UserTrip.create(user: current_user, trip: @trip, accepted: true)
  #   @trip.save
  # end

  private

  def trip_params
    params.require(:trip).permit(:start_date, :end_date, :title)
  end

  def sign_up_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

  def init_mark_down_parser
    renderer = Redcarpet::Render::HTML.new(no_images: true)
    @markdown = Redcarpet::Markdown.new(renderer)
  end
end

app/views/trips/index.html.erb
<div class="container">
  <h2>Les sorties prévues:</h2>

  <div class="row">
    <% @trips.each do |trip|  %>
    <div class="col-xs-12 col-sm-6 col-md-4" style="padding: 10px;">
      <div class="card trip-element" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= trip.itinerary.picture_url %>');">
        <%= link_to " ", trip_path(trip), class: "card-link" %>
        <div class="card-category card-element-invisible"><%= trip.itinerary.activities.join(", ") %></div>
        <div class="card-description">
          <div class="card-infos">
            <h2><%= trip.title %></h2>
            <p class="card-comment card-element-invisible">organisé par <%= trip.user.user_name %> du <%= trip.start_date %> au <%= trip.end_date %></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/trips/my_trips.html.erb
<h2>Mes sorties</h2>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
  <% @my_trips.each do |trip| %>
  <div class="trip trip-element">
    <h4><%= trip.title %> du <%= trip.start_date %> au <%= trip.end_date %></h4>
    <% if trip.user_trips.empty? %>
      <p>Personne ne veut venir avec toi, gros looser.</p>
      <p>==> Partage le trip sur <a href="https://www.facebook.com/" target="blank"><i class="fab fa-facebook-f"></i></a></p>
      <br>
    <% else %>
      <% trip.user_trips.each do |request| %>
        <div class="message">
          <img class="avatar-large" src=<% @trip.user.avatar %>>
          <div class="message-name">
            <h3><%= request.user.user_name %></h3>
            <p><%= request.created_at.to_s.first(9) %></p>
          </div>
          <div class="message-body">
            <p><strong><%= request.user.messages.last.content %></strong></p>
          </div>
          <div>
            <% if request.state == "demandé"  %>
              <%= link_to('Valider', accept_user_trip_path(request), method: :patch, class: "btn btn-success visible-btn") %>
              <%= link_to('Refuser, il est moche', decline_user_trip_path(request), method: :patch, class: "btn btn-danger visible-btn") %>
            <% elsif request.state == "refusé" %>
              <span>Refusé</span>
            <% else %>
              <span>Déjà validé!</span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  <% end %>
  </div>
</div>

</div>

app/views/trips/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/1134188/pexels-photo-1134188.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
  <div class="form-container">
    <div class ="col-xs-12 col-sm-6 col-md-6 col-md-offset-3 ">
      <div class="my-form" >
        <div class="my-form-title" >
          <h2 class ="text-center">Nouvelle sortie</h2>
        </div>
        <div class="my-form-body">
         <%=simple_form_for [@itinerary, @trip],
         wrapper: :horizontal_form,
         wrapper_mappings: {
          date: :horizontal_multi_select,
        } do |f| %>
        <%= f.error_notification %>
        <%= f.input :title, label: "Nomme ta sortie!" %>
        <%= f.input :start_date, as: :date, html5: true, label: "Date de départ:"  %>
        <%= f.input :end_date, as: :date, html5: true, label: "Date de retour:" %>
        <div class="form-group row mb-0">
          <div class="col-sm-9 offset-sm-3">
           <div class="my-buttons">
            <%= f.button :submit, label: "Créer", class: "btn-primary outline" %>
            <%= link_to "Retour", itineraries_path, class: "btn btn-primary outline" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/trips/show.html.erb
<% itinerary = @trip.itinerary %>
<div class="container">
  <div class="flex-container">
   <div class="flex-object">
     <div class="card-iti">
      <%= image_tag @trip.itinerary.picture_url %>
      <div class="card-category">
        <%= itinerary.activities.join(", ") %>
        <p> par <%= @trip.user.user_name %></p><p> du <%= @trip.start_date %> au <%= @trip.end_date %> </p>

        <ul class="list-inline">
          <!-- <li class="list-inline-item">Avec:</li> -->
          <% @users.each do |user| %>
          <li class="list-inline-item">
            <% if user.picture.file.nil? %>
            <img src="https://loremflickr.com/320/320?lock=1" class="avatar dropdown-toggle" id="navbar-mountain-menu" data-toggle="dropdown">
            <% else %>
            <img src="<%= cl_image_path user.picture, height: 300, width: 400, crop: :fill %>" class="avatar dropdown-toggle" id="navbar-mountain-menu" data-toggle="dropdown">
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="card-iti-description">
        <ul class="list-group">
        <li class="list-group-item trans"><h4 class="text-center"><%= @trip.title %> </h4> </li>
        <li class="list-group-item trans"> <%= @trip.itinerary.title %> </li>
        <% if @trip.itinerary.diffculty != nil %>
          <li class="list-group-item trans">Difficulté: <%= @trip.itinerary.diffculty %></li>
        <% end %>
        <% if @trip.itinerary.elevation_max != nil %>
          <li class="list-group-item trans">Altitude maximale: <%= @trip.itinerary.elevation_max %>mètres</li>
        <% end %>

        <% if @trip.itinerary.height_diff_up != nil %>
          <li class="list-group-item trans">Dénivelé: <%= @trip.itinerary.height_diff_up %>mètres</li>
        <% end %>

        <% if @trip.itinerary.number_of_outings != nil %>
          <li class="list-group-item trans">Outings: <%= @trip.itinerary.number_of_outings %></li>
        <% end %>

            <% if @users.empty? %>
            <li class="list-group-item trans"><span id="participants">Aucun participant pour l'instant.</span></li>
          <% else %>
            <li class="list-group-item trans"><span id="participants">Participants: <%= @users.map { |user| user.user_name }.join(" ,") %></span></li>
        <% end %>
        </ul>

      </div>
      <div>

        <!-- Button trigger modal -->
        <button type="button " class="btn btn-primary outline card-button" data-toggle="modal" data-target="#myModal">
          Je veux participer
        </button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="myModalLabel" style="color:black;">Votre message</h4>
                </div>
                <div class="modal-body">
                  <%= simple_form_for [@trip, @user_trip] do |f| %>
                  <%= f.input :default_message, placeholder: "Pourquoi voulez-vous vous joindre à cette sortie ?", label: false %>
                </div>
                <div class="modal-footer">
                  <div><%= f.submit :Demander, class: "btn btn-primary outline" %></div>
                </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="flex-object description trip-element">
      <h4>Description</h4>
      <%= render partial: "./itineraries/description", locals: {itinerary: itinerary} %>
    </div>


    <!-- Add for demo -->
    <div class="flex-object trip-element">
      <h4>Météo</h4>
      <img src='https://res.cloudinary.com/dcr8ffyyv/image/upload/v1550848162/weather_placeholder.png' alt="Météo">
    </div>


    <div class="flex-object">
      <iframe src=<%= "https://fatmap.com/@#{itinerary.coord_lat},#{itinerary.coord_long},#{itinerary.elevation_max},-35.9049826,92.6848191,2388.9221056,normal" %> frameborder="" allowfullscreen="" width="100%" height="600"></iframe>
    </div>
  </div>
</div>