config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resources :itineraries, only: [:index, :show] do
    resources :trips, only: [:new, :create]
  end

  resources :trips, only: [:show, :index, :edit, :update] do
    resources :messages, only: [:index, :new, :create, :update, :edit]
    resources :user_trips, only: [:create]
  end

  resources :user_trips, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  get "my_trips", to: "trips#my_trips"

end

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('mountains.png') %>
    <title>Mountain Trip</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <div id="main-frame">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1464207687429-7505649dae38?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60');">
        <div class="banner-content">
          <h1>Mountain Trip</h1>
          <p>You will never walk alone</p>
          <div style="position: relative; height: 155px; width: 400px;">
            <%= form_tag itineraries_path, method: :get, class: "form-group" do %>
              <%= text_field_tag :address,
                params[:address],
                class: "form-control",
                id: "itinerary_address",
                placeholder: "Adresse de départ"
              %>
              <%= select_tag :activity,
                options_for_select( Itinerary::ACTIVITIES_MAPPING.map {|k, v| [v, k]},
                params[:product]),
                class: "form-control",
                include_blank: "Activité"
              %>
              <div class="my-buttons">
              <%= submit_tag "Créer une sortie", class: "btn btn-primary outline" %>
              <%= submit_tag "Rejoindre une sortie", formaction: trips_path, class: "btn btn-primary outline" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="container">
        <h3>Les sorties à venir:</h3>
        <div class="row">
          <% @trips.each do |trip| %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= trip.itinerary.picture_url %>');">
                <%= link_to " ", trip_path(trip), class: "card-link" %>
                <div class="card-category card-element-invisible"><%= trip.itinerary.activities.join(", ") %></div>
                <div class="card-description">
                  <div class="card-infos">
                    <h2><%= link_to(trip.title, itinerary_path(trip.itinerary)) %></h2>
                    <%= link_to('', itinerary_path(trip.itinerary), class: "card-link") %>
                    <p class="card-comment card-element-invisible">Organisé par <%= link_to(trip.user.user_name, itinerary_path(trip.itinerary))%> du <%= trip.start_date %> au <%= trip.end_date %></p>
                  </div>
                </div>
                <img class="card-user-avatar card-element-invisible" src= <%= trip.user.avatar %>>
                <%= link_to " ", trip_messages_path(trip), class: "fas fa-envelope card-icon card-element-invisible" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <%= render 'shared/footer' %>
      <%= stylesheet_pack_tag 'application' %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
    </div>
  </body>
</html>